### ISSUE TITLE
Tools required for developers

### ISSUE THREAD

**Issue by MartinErwig** [The-Code-In-Sheep-s-Clothing/bogl-docs#19]
It would be helpful to mention which software and tools are required to successfully execute the instructions on:

[https://bogl.engr.oregonstate.edu/technical/developing.html](https://bogl.engr.oregonstate.edu/technical/developing.html)

**Comment by montymxb** [comment]
Added a pre-requisite section to the [dev](https://bogl.engr.oregonstate.edu/technical/developing.html) page to clarify requirements & offer installation options.
