### ISSUE TITLE
"This tutorial covers" consistency

### ISSUE THREAD

**Issue by Aidenjn** [The-Code-In-Sheep-s-Clothing/bogl-docs#25]
For consistency, I would like all the items under "**:leaves: This tutorial covers:**" to be nouns. Ex: "Defining Values" should be "Value Definitions". These items should not be super specific. If they are too specific/weird to turn into a noun, they should probably be under "**:deciduous_tree: At the end, you should be able to:**".

**Comment by garrettberliner** [comment]
Hey Aiden! I just made the changed on my end, what commands do I use to upload them again?

**Comment by Aidenjn** [comment]
To upload your commit you need to use the command **git push**. Make sure that when you push you are on your own (non-master) branch. Once you have pushed you can make a pull request from the github repository page.
