### ISSUE TITLE
Improving tutorial objectives

### ISSUE THREAD

**Issue by Aidenjn** [The-Code-In-Sheep-s-Clothing/bogl-docs#26]
Things under the "**:deciduous_tree: At the end, you should be able to:**" section should be measurable learning objectives. That means we want to avoid vague verbs that are not demonstrable like "understand". When in doubt, use a word from the middle section of [this wheel](http://reinventenglish.com/wp-content/uploads/2018/03/ep-blooms-wheel.jpg) when phrasing your objectives.

**Comment by garrettberliner** [comment]
Hey Aiden! Just like the last task, I have it done and don't remember the github commands to upload it.
